### ISSUE TITLE
Problemas ao usar SOAP > ObterProposicaoPorID - serviço retorna HTML

### ISSUE THREAD

**Issue by lucastx** [labhackercd/dados-abertos#218]
Olá,

Desde a semana passada, temos tido erros no uso da API. Usamos esse trecho de código já há cerca de dois anos e só agora ele foi parar de funcionar. O SUDS (biblioteca Python para abstração do SOAP) não está conseguindo mais baixar proposições da Câmara no nosso sistema.

Para reproduzir (utilizando python 2.7):

```
import suds.client
soap_client = suds.client.Client("https://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx?wsdl")
soap_object = soap_client.service.ObterProposicaoPorID("2190752")
```

É exibido o seguinte erro:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/radarlegislativo/main/tasks.py", line 33, in queue_download
    fetch_camara_project(id_no_site, tags=tags, publish=publish)
  File "/srv/radarlegislativo/main/fetcher.py", line 254, in fetch_camara_project
    soap_object = soap_client.service.ObterProposicaoPorID(id_camara)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 661, in process_reply
    replyroot = _parse(reply)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 832, in _parse
    return Parser().parse(string=string)
  File "/usr/local/lib/python2.7/site-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 224, in feed
    self._err_handler.fatalError(exc)
  File "/usr/local/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
SAXParseException: mismatched tag
```

Ao ligar uma flag de DEBUG do SUDS, as seguintes informações complementares são exibidas:

```
URL: http://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx
HEADERS: {'SOAPAction': '"http://www.camara.gov.br/SitCamaraWS/Proposicoes/ObterProposicaoPorID"', 'Content-Type': 'text/xml; charset=utf-8', 'Content-type': 'text/xml; charset=utf-8', 'Soapaction': '"http://www.camara.gov.br/SitCamaraWS/Proposicoes/ObterProposicaoPorID"'}
MESSAGE:
<?xml version="1.0" encoding="UTF-8"?><SOAP-ENV:Envelope xmlns:ns0="http://www.camara.gov.br/SitCamaraWS/Proposicoes" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/"><SOAP-ENV:Header/><ns1:Body><ns0:ObterProposicaoPorID><ns0:idProp>50</ns0:idProp></ns0:ObterProposicaoPorID></ns1:Body></SOAP-ENV:Envelope>
```

Esse parece ser a página que foi de fato baixada. Pelo que me parece, a biblioteca esperava um arquivo XML mas recebeu de volta um HTML:

```
<html>
    <head><link rel="alternate" type="text/xml" href="/SitCamaraWS/Proposicoes.asmx?disco" />
    <style type="text/css">
                BODY { color: #000000; background-color: white; font-family: Verdana; margin-left: 0px; margin-top: 0px; }
                [...]
</style>

    <title>        Proposicoes Web Service</title></head>
  <body>
    <div id="content">
      <p class="heading1">Proposicoes</p><br>
      <span>
          <p class="intro">The following operations are supported.  For a formal definition, please review the <a href="Proposicoes.asmx?WSDL">Service Description</a>. </p>
              <ul>
              <li>
                <a href="Proposicoes.asmx?op=ListarAutoresProposicao">ListarAutoresProposicao</a>
                <span>
                  <br>Lista Autores de um determinada proposição
                </span>
              </li>
              <p>
              <li>
                <a href="Proposicoes.asmx?op=ListarProposicoes">ListarProposicoes</a>
              </li>
              <p>
              
              [...]
              
              <li>
                <a href="Proposicoes.asmx?op=obterHierarquiaProposicao">obterHierarquiaProposicao</a>
              </li>
              <p>
              <li>
                <a href="Proposicoes.asmx?op=obterProposicaoPrincipal">obterProposicaoPrincipal</a>
              </li>
              <p>
</ul>
      </span>
    <span>
    </span>
  </body>
</html>
```

O que pode estar acontecendo?

Abraços e obrigado

**Comment by fgmandarino** [comment]
Prezado, boa tarde. Eu trabalho na equipe dos dados abertos da Câmara dos Deputados. 
A gente fez alguns testes aqui nessa biblioteca 'suds' e nos parece que como mudamos o acesso para HTTPS, a biblioteca precisa de um parâmetro adicional para funcionar corretamente. 

Tente usar da seguinte maneira:

import suds.client
soap_client = suds.client.Client("https://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx?wsdl", location="https://www.camara.leg.br/SitCamaraWS/Proposicoes.asmx")
soap_object = soap_client.service.ObterProposicaoPorID("2190752")

obs: Foi usado python 2.7 no windows com suds 0.4 e suds-jurko 0.6

Pelo que verificamos, sem esse parâmetro adicional, a biblioteca faz o post por  http na porta 80 sem o TLS. Adicionando o parâmetro, a conexão usa a porta 443 com TLS conforme esperado.

**Comment by lucastx** [comment]
Olá @fgmandarino. O parâmetro extra que você indicou funcionou; consegui fazer a requisição sem problemas.

Obrigado pela resposta!
