### ISSUE TITLE
Erro na consulta de proposições: "Dados são Null"

### ISSUE THREAD

**Issue by urbanobm** [labhackercd/dados-abertos#48]
Bom dia!

Está ocorrendo um erro na consulta de proposições informando que os valores passados são nulos entretanto todos os parâmetros estão preenchidos com valores válidos. Segue o erro retornado: 

_**Dados são Null. Não é possível chamar este método ou esta propriedade em valores Null. - System.Data -    at System.Data.SqlTypes.SqlInt32.get_Value()
   at System.Data.SqlClient.SqlDataReader.GetInt32(Int32 i)
   at CamaraWSSemComponente.Orgaos.ObterIntegraComissoesRelator(String tipo, String numero, String ano)**_

Exemplo de URL de requisição que retornou o erro:

http://www.camara.gov.br/SitCamaraWS/Orgaos.asmx/ObterIntegraComissoesRelator?tipo=PL&numero=6157&ano=2013

Gentileza verificar.
Obrigado.

**Comment by CeninCD** [comment]
Olá, Urbano!

O problema foi reproduzido e confirmado para este PL. Você teria alguns outros exemplos de proposições que estão causando isso?

Testei alguns outros projetos arquivados, outros do mesmo ano, mas estes não causaram o mesmo erro e ainda não consegui identificar o que poderia ser uma causa para o problema...

Obrigado e abraço!

Fabricio Rocha
Cenin

**Comment by urbanobm** [comment]
Boa tarde Fabrício! Obrigado pela atenção!

Não tenho outros exemplos, apesar de acreditar que possam existir.
A impressão que dá é que algum dado da proposição está nulo e pode estar causando o problema.
Abraço!

Urbano
